apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rule-of-law-reporting
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - rolr.lb.djnd.si
      secretName: rule-of-law-reporting-tls
  rules:
    - host: rolr.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rule-of-law-reporting
                port:
                  number: 80
